### PR TITLE
Add compress option

### PR DESCRIPTION
**Pull request by Rommeo85**

### CODE REVIEW

**Comment by robotlovesyou** [comment]
Hi, this looks like a good idea but it would need to be documented in the readme and added to the tests before I could merge it.

Thanks

Andy

**Comment by mathiasschopmans** [comment]
+1

**Comment by vict-shevchenko** [comment]
+ 1

**Comment by MattCBowman** [comment]
I'd rather not see this be part of this library. There's a contrib module that already can handle this, set it to run after this task. https://github.com/gruntjs/grunt-contrib-cssmin

**Comment by vict-shevchenko** [comment]
Yea, then I`d recommend this lib should not change the format of CSS file it is processing.

I have run a CSSMIN, and after that I use CSS SPLIT, my output files are no more minified. It looks a bit strange to  min->split->min.

What do you think?

**Comment by MattCBowman** [comment]
I see your point, it certainly is less than ideal to have the css files handled by this task be modified in any way other than being split to fit into the IE rule limit.
You could create two tasks in cssmin - one that concatenates your files, and one that minifies them, so it'd be more like cssmin:concat->split->cssmin:minify.

**Comment by robotlovesyou** [comment]
Yeah it's a fair comment. I was thinking maybe it would be useful because you can't predetermine your split artefacts but then you would just use a glob with cssmin wouldn't you? I think I may have been having a slow day. ;-)

At this stage I can't see the requested tests turning up anyway.

**Pull request closed without merging**
